@ECHO OFF 
PUSHD %~DP0
SET CURDIR=%CD%
PUSHD ..
SET TOPDIR=%CD%
POPD
POPD

SET GDAL_ROOT=%TOPDIR%\OSGeo4W
SET GDAL_PAM_PROXY_DIR=%TEMP%
SET GDAL_DATA=%GDAL_ROOT%\apps\gdal-16\share\gdal
SET GEOTIFF_CSV=%GDAL_ROOT%\share\epsg_csv
SET PROJ_LIB=%GDAL_ROOT%\share\proj
SET GDAL_DRIVER_PATH=%GDAL_ROOT%\apps\gdal-16\bin\gdalplugins

SET PYTHONHOME=%GDAL_ROOT%\apps\Python25
SET PYTHONPATH=%PYTHONHOME%\Lib\lib-tk
SET PYTHONPATH=%PYTHONHOME%\Lib\site-packages\pywin32_system32;%PYTHONHOME%\Lib\site-packages\win32;%PYTHONHOME%\Lib\site-packages\win32\lib;%PYTHONHOME%\Lib\site-packages\pythonwin;%PYTHONPATH%
SET PYTHONPATH=%GDAL_ROOT%\bin;%GDAL_ROOT%\apps\gdal-16\pymod;%PYTHONPATH%
SET PYTHONPATH=%CURDIR%\lib;%PYTHONPATH%

PATH=%GDAL_ROOT%\bin;%PATH%
PATH=%GDAL_ROOT%\apps\gdal-16\bin;%PATH%
PATH=%GDAL_DRIVER_PATH%;%PATH%
PATH=%PYTHONPATH%;%PATH%
PATH=%PYTHONHOME%;%PATH%
PATH=%CURDIR%;%PATH%

