@ECHO OFF 
PUSHD %~DP0
SET CURDIR=%CD%
PUSHD ..
SET TOPDIR=%CD%
POPD
POPD

SET PYTHONHOME=%TOPDIR%\bin\Python27
SET GDALHOME=%PYTHONHOME%\Lib\site-packages\osgeo

set PYTHONNOUSERSITE=1

SET PYTHONPATH=%PYTHONHOME%\Lib;%PYTHONHOME%\Lib\site-packages
SET PYTHONPATH=%PYTHONHOME%\Lib\site-packages\pywin32_system32;%PYTHONHOME%\Lib\site-packages\win32;%PYTHONHOME%\Lib\site-packages\win32\lib;%PYTHONHOME%\Lib\site-packages\pythonwin;%PYTHONPATH%
SET PYTHONPATH=%PYTHONHOME%\Lib\lib-tk;%PYTHONPATH%
SET PYTHONPATH=%PYTHONHOME%\Lib\site-packages\pywin32_system32;%PYTHONHOME%\Lib\site-packages\win32;%PYTHONHOME%\Lib\site-packages\win32\lib;%PYTHONHOME%\Lib\site-packages\pythonwin;%PYTHONPATH%
SET PYTHONPATH=%CURDIR%;%PYTHONPATH%

SET GDAL_API_PROXY=ecw,sid,jp2,j2k,ntf
rem SET GDAL_API_PROXY_CONN_POOL=NO
rem SET GDAL_PAM_PROXY_DIR=%TEMP%
SET GDAL_DATA=%GDALHOME%\data\gdal
SET GEOTIFF_CSV=%GDAL_DATA%
REM SET PROJ_LIB=%GDAL_ROOT%\share\proj
SET GDAL_DRIVER_PATH=%GDALHOME%\gdalplugins

SET path=
SET path=%WINDIR%;%WINDIR%\system32
PATH=%GDALHOME%;%GDAL_DRIVER_PATH%;%PATH%

PATH=%GDAL_DRIVER_PATH%;%PATH%
PATH=%PYTHONPATH%;%PATH%
PATH=%PYTHONHOME%;%PATH%
PATH=%CURDIR%;%PATH%

SET GDAL_SKIP=
SET _GDAL_SKIP=JP2MrSID JP2OpenJPEG
for /f "tokens=1" %%D IN ('gdalinfo  --formats^|findstr /r "%_GDAL_SKIP%"') DO SET GDAL_SKIP=!GDAL_SKIP! %%D

